name: nid
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.24
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.4.0
  cool_alert: ^1.1.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  email_auth: ^0.0.1+4
  equatable: ^2.0.3
  firebase_analytics: ^8.3.1
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_database: ^7.1.2
  firebase_messaging: ^11.2.4
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_dotenv: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^9.1.5
  flutter_native_splash: ^1.1.8+4
  flutter_screenutil: ^5.0.0+2
  flutter_slidable: ^0.6.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  hydrated_bloc: ^7.0.1
  image_picker: ^0.8.3+3
  import_sorter: ^4.6.0
  measure_size: ^2.0.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  rive: ^0.7.23
  rxdart: ^0.27.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  syncfusion_flutter_datepicker: ^19.2.57
  table_calendar: ^3.0.1
  timeago: ^3.1.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  color_dart: "#1a1a1a"
  image_dart: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"

import_sorter:
  emojis: true # Optional, defaults to false

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/rives/
    - .env

  fonts:
    # - family: Muli
    #   fonts:
    #     - asset: assets/fonts/muli/Muli.ttf
    #     - asset: assets/fonts/muli/Muli-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/muli/Muli-BoldItalic.ttf
    #       weight: 600
    #     - asset: assets/fonts/muli/Muli-Semi-BoldItalic.ttf
    #       weight: 500
    #     - asset: assets/fonts/muli/Muli-Italic.ttf
    #       weight: 400
    - family: Avenir Next Rounded Pro
      fonts:
        - asset: assets/fonts/AvenirNext/avenirnextroundedpro-demi.woff.ttf
          weight: 600
        - asset: assets/fonts/AvenirNext/AvenirNextRoundedPro-Med.ttf
          weight: 500
        - asset: assets/fonts/AvenirNext/AvenirNextRoundedPro-Reg.ttf
          weight: 400

    - family: Symbola
      fonts:
        - asset: assets/fonts/Symbola.ttf
